"""
Create a full-process demo video:
1. Show the original PPTX slides statically (3 seconds each).
2. Show a transition card explaining the Skill is converting the deck.
3. Play the final narrated video generated by RedNote Studio.
"""

import subprocess
import sys
from pathlib import Path

# Add local backend to path.
BACKEND = Path(__file__).resolve().parent / "backend"
sys.path.insert(0, str(BACKEND))

from app.core import renderer


PPT_DIR = Path(__file__).resolve().parent
STATIC_DURATION = 3.0  # seconds per slide
TRANSITION_DURATION = 4.0


def _find_latest_output_dir() -> Path:
    outputs_dir = PPT_DIR / "data" / "outputs"
    if not outputs_dir.exists():
        raise FileNotFoundError("No outputs directory found.")
    dirs = [d for d in outputs_dir.iterdir() if d.is_dir()]
    if not dirs:
        raise FileNotFoundError("No output job directories found.")
    return max(dirs, key=lambda d: d.stat().st_mtime)


def _build_static_video(slide_images: list[Path], output_path: Path) -> Path:
    """Build a silent video that shows each slide for STATIC_DURATION seconds."""
    inputs: list[str] = []
    for img in slide_images:
        inputs.extend(["-loop", "1", "-t", str(STATIC_DURATION), "-i", str(img)])

    filter_parts: list[str] = []
    for idx in range(len(slide_images)):
        filter_parts.append(
            f"[{idx}:v]scale=1920:1080:force_original_aspect_ratio=decrease,"
            f"pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1,"
            f"fps=30,format=yuv420p,setpts=PTS-STARTPTS[v{idx}];"
        )
    concat_inputs = "".join(f"[v{idx}]" for idx in range(len(slide_images)))
    filter_parts.append(f"{concat_inputs}concat=n={len(slide_images)}:v=1:a=0[vv]")

    cmd = [
        "ffmpeg",
        "-y",
        "-nostdin",
        *inputs,
        "-filter_complex",
        "".join(filter_parts),
        "-map",
        "[vv]",
        "-an",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        str(output_path),
    ]
    subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return output_path


def _build_transition_card(output_path: Path) -> Path:
    """Build a short silent card explaining the conversion step."""
    W, H = 1920, 1080
    from PIL import Image, ImageDraw, ImageFont

    def _font(size: int):
        for path in [
            "/System/Library/Fonts/PingFang.ttc",
            "/System/Library/Fonts/STHeiti Light.ttc",
        ]:
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
        return ImageFont.load_default()

    img = Image.new("RGB", (W, H), (25, 25, 35))
    draw = ImageDraw.Draw(img)

    title = "正在使用 RedNote Studio Skill"
    subtitle = "将这份 PPTX 转换为带中文语音讲解的视频"
    steps = "提取标题要点 → 生成中文讲稿 → 合成神经语音 → 输出 1080P MP4 + 字幕"

    title_font = _font(72)
    sub_font = _font(44)
    step_font = _font(34)

    def _center(text: str, font, y: int):
        bbox = draw.textbbox((0, 0), text, font=font)
        tw = bbox[2] - bbox[0]
        draw.text(((W - tw) // 2, y), text, font=font, fill=(255, 255, 255))

    _center(title, title_font, 360)
    _center(subtitle, sub_font, 480)
    _center(steps, step_font, 600)

    img.save(output_path, "PNG")

    # Convert to video.
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-nostdin",
            "-loop", "1",
            "-t", str(TRANSITION_DURATION),
            "-i", str(output_path),
            "-vf", "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080,setsar=1,fps=30,format=yuv420p",
            "-an",
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            str(output_path.with_suffix(".mp4")),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return output_path.with_suffix(".mp4")


def _concat_videos(parts: list[Path], output_path: Path) -> Path:
    """Concatenate MP4 parts using ffmpeg concat demuxer."""
    list_file = output_path.with_suffix(".txt")
    list_file.write_text(
        "\n".join(f"file '{p.resolve()}'" for p in parts), encoding="utf-8"
    )
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-nostdin",
            "-f", "concat",
            "-safe", "0",
            "-i", str(list_file),
            "-c", "copy",
            str(output_path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return output_path


def main():
    work_dir = _find_latest_output_dir()
    slide_images = sorted(work_dir.glob("slide_*.png"))
    if not slide_images:
        raise FileNotFoundError("No slide images found in output directory.")

    narrated_video = PPT_DIR / "rednote-existing-demo-output.mp4"
    if not narrated_video.exists():
        raise FileNotFoundError(
            f"Narrated video not found: {narrated_video}. "
            "Run generate_existing_ppt_demo.py first."
        )

    temp_dir = PPT_DIR / "data" / "outputs" / "full_process_temp"
    temp_dir.mkdir(parents=True, exist_ok=True)

    static_video = temp_dir / "static.mp4"
    transition_video = temp_dir / "transition.mp4"
    final_output = PPT_DIR / "rednote-full-process-demo-output.mp4"

    print("[1/3] Building static PPT showcase video...")
    _build_static_video(slide_images, static_video)

    print("[2/3] Building transition card...")
    _build_transition_card(temp_dir / "transition.png")

    print("[3/3] Concatenating static + transition + narrated video...")
    _concat_videos([static_video, transition_video, narrated_video], final_output)

    print(f"\nFull-process demo video saved to: {final_output}")
    print(f"Duration breakdown: {len(slide_images) * STATIC_DURATION:.0f}s static + "
          f"{TRANSITION_DURATION:.0f}s transition + narrated video")


if __name__ == "__main__":
    main()
