"""
Create a full-process demo video:
1. Export the original PPTX slides to high-res PNGs using LibreOffice + pdftoppm.
2. Show the original PPTX slides statically (3 seconds each) with a silent audio track.
3. Show a transition card explaining the Skill is converting the deck (with silent audio).
4. Play the final narrated video generated by RedNote Studio.
"""

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# Add local backend to path.
BACKEND = Path(__file__).resolve().parent / "backend"
sys.path.insert(0, str(BACKEND))

from app.core import renderer


PPT_DIR = Path(__file__).resolve().parent
STATIC_DURATION = 3.0  # seconds per slide
TRANSITION_DURATION = 4.0


def _check_tool(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise RuntimeError(f"Required tool not found: {name}. Please install it.")
    return path


def _export_pptx_to_pngs(pptx_path: Path, output_dir: Path) -> list[Path]:
    """Export each PPTX slide to a high-resolution PNG using LibreOffice + pdftoppm."""
    _check_tool("soffice")
    _check_tool("pdftoppm")

    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Convert PPTX to PDF with LibreOffice.
    pdf_path = output_dir / "slides.pdf"
    subprocess.run(
        [
            "soffice",
            "--headless",
            "--convert-to", "pdf",
            "--outdir", str(output_dir),
            str(pptx_path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )

    # LibreOffice names the PDF after the input file; find it.
    pdf_files = list(output_dir.glob("*.pdf"))
    if not pdf_files:
        raise FileNotFoundError("LibreOffice did not produce a PDF.")
    pdf_file = pdf_files[0]

    # 2. Convert PDF pages to PNGs at 300 DPI.
    pages_prefix = output_dir / "page"
    subprocess.run(
        [
            "pdftoppm",
            "-png",
            "-r", "300",
            str(pdf_file),
            str(pages_prefix),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )

    pages = sorted(output_dir.glob("page-*.png"))
    if not pages:
        raise FileNotFoundError("pdftoppm did not produce PNG pages.")
    return pages


def _build_silent_video(images: list[Path], duration_per_image: float, output_path: Path) -> Path:
    """Build a silent 1080p30 video from images, each shown for duration seconds."""
    inputs: list[str] = []
    for img in images:
        inputs.extend(["-loop", "1", "-t", str(duration_per_image), "-i", str(img)])

    filter_parts: list[str] = []
    for idx in range(len(images)):
        filter_parts.append(
            f"[{idx}:v]scale=1920:1080:force_original_aspect_ratio=decrease,"
            f"pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1,"
            f"fps=30,format=yuv420p,setpts=PTS-STARTPTS[v{idx}];"
        )
    concat_inputs = "".join(f"[v{idx}]" for idx in range(len(images)))
    filter_parts.append(f"{concat_inputs}concat=n={len(images)}:v=1:a=0[vv]")

    cmd = [
        "ffmpeg",
        "-y",
        "-nostdin",
        *inputs,
        "-filter_complex",
        "".join(filter_parts),
        "-map", "[vv]",
        "-an",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        str(output_path),
    ]
    subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return output_path


def _add_silent_audio(video_path: Path, output_path: Path) -> Path:
    """Add a silent AAC audio track to a video so concat later preserves audio."""
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-nostdin",
            "-i", str(video_path),
            "-f", "lavfi",
            "-i", "anullsrc=r=48000:cl=mono",
            "-c:v", "copy",
            "-c:a", "aac",
            "-b:a", "128k",
            "-ar", "48000",
            "-shortest",
            str(output_path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return output_path


def _build_transition_card(output_path: Path) -> Path:
    """Build a short transition card with silent audio."""
    W, H = 1920, 1080
    from PIL import Image, ImageDraw, ImageFont

    def _font(size: int):
        for path in [
            "/System/Library/Fonts/PingFang.ttc",
            "/System/Library/Fonts/STHeiti Light.ttc",
        ]:
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
        return ImageFont.load_default()

    img = Image.new("RGB", (W, H), (25, 25, 35))
    draw = ImageDraw.Draw(img)

    title = "正在使用 RedNote Studio Skill"
    subtitle = "将这份 PPTX 转换为带中文语音讲解的视频"
    steps = "提取标题要点 → 生成中文讲稿 → 合成神经语音 → 输出 1080P MP4 + 字幕"

    title_font = _font(72)
    sub_font = _font(44)
    step_font = _font(34)

    def _center(text: str, font, y: int, fill=(255, 255, 255)):
        bbox = draw.textbbox((0, 0), text, font=font)
        tw = bbox[2] - bbox[0]
        draw.text(((W - tw) // 2, y), text, font=font, fill=fill)

    _center(title, title_font, 360)
    _center(subtitle, sub_font, 480)
    _center(steps, step_font, 600)

    png_path = output_path.with_suffix(".png")
    img.save(png_path, "PNG")

    # Convert PNG to silent video.
    silent_video = output_path.with_stem(output_path.stem + "_silent")
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-nostdin",
            "-loop", "1",
            "-t", str(TRANSITION_DURATION),
            "-i", str(png_path),
            "-vf", "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080,setsar=1,fps=30,format=yuv420p",
            "-an",
            "-c:v", "libx264",
            "-pix_fmt", "yuv420p",
            str(silent_video),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )

    # Add silent audio track.
    _add_silent_audio(silent_video, output_path)
    silent_video.unlink(missing_ok=True)
    return output_path


def _concat_videos(parts: list[Path], output_path: Path) -> Path:
    """Concatenate MP4 parts with both video and audio streams."""
    list_file = output_path.with_suffix(".txt")
    list_file.write_text(
        "\n".join(f"file '{p.resolve()}'" for p in parts), encoding="utf-8"
    )
    subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-nostdin",
            "-f", "concat",
            "-safe", "0",
            "-i", str(list_file),
            "-c", "copy",
            str(output_path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return output_path


def main():
    pptx_path = PPT_DIR / "RedNote Studio - 小红书 AI 视频笔记生成 Skill.pptx"
    if not pptx_path.exists():
        raise FileNotFoundError(f"PPTX not found: {pptx_path}")

    narrated_video = PPT_DIR / "rednote-existing-demo-output.mp4"
    if not narrated_video.exists():
        raise FileNotFoundError(
            f"Narrated video not found: {narrated_video}. "
            "Run generate_existing_ppt_demo.py first."
        )

    temp_dir = Path(tempfile.mkdtemp(prefix="rednote_full_process_"))
    final_output = PPT_DIR / "rednote-full-process-demo-output.mp4"

    try:
        print("[1/4] Exporting original PPTX slides to real PNGs via LibreOffice...")
        slide_images = _export_pptx_to_pngs(pptx_path, temp_dir / "slides")
        print(f"      Exported {len(slide_images)} slides.")

        static_silent = temp_dir / "static_silent.mp4"
        static_with_audio = temp_dir / "static_with_audio.mp4"
        transition_with_audio = temp_dir / "transition_with_audio.mp4"

        print("[2/4] Building static PPT showcase video...")
        _build_silent_video(slide_images, STATIC_DURATION, static_silent)
        _add_silent_audio(static_silent, static_with_audio)

        print("[3/4] Building transition card...")
        _build_transition_card(transition_with_audio)

        print("[4/4] Concatenating static + transition + narrated video...")
        _concat_videos([static_with_audio, transition_with_audio, narrated_video], final_output)

        print(f"\nFull-process demo video saved to: {final_output}")
        print(f"Duration breakdown: {len(slide_images) * STATIC_DURATION:.0f}s static + "
              f"{TRANSITION_DURATION:.0f}s transition + narrated video")
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
